= 깃 배우기

이 페이지는 새티스팩토리 모딩의 맥락에서 깃에 대한 간략한 소개와
모딩 프로젝트에서 효율성을 높이는 방법을 제공합니다.

== 깃(Git)이란?

**깃**은 파일의 변경 사항을 추적하여 파일의 서로 다른
'수정본' 간의 변화를 관리하기 위해 만들어진 오픈 소스 소프트웨어입니다.
자세한 내용은 https://git-scm.com/about[깃 웹사이트]를 참고하십시오.

== 깃 저장소를 사용하는 이유

장점:

- 코드의 과거 버전으로 쉽게 돌아가 기능을 테스트할 수 있습니다.
- 변경 사항을 추적하여 릴리스에 대한 패치 노트를 작성할 수 있습니다.
- 다른 사람과 소스 코드를 쉽게 공유할 수 있습니다.
- 파일을 백업하여 파일이 손상되거나 컴퓨터에 접근할 수 없게 되어도 사용할 수 있습니다.
- 오랜 휴식 후 모딩으로 돌아갈 때 파일을 잃어버릴 가능성을 줄입니다.
- 버전 관리 사용은 모든 코더에게 유용한 기술입니다.

단점:

- 배워야 할 도구가 하나 더 생깁니다.

== 깃과 깃허브의 차이

"깃"과 "깃허브", "깃랩(GitLab)"과 같은 플랫폼 간의 차이를 이해하는 것이 중요합니다.

**깃**은 파일 관리를 가능하게 하는 소프트웨어로, 로컬 파일 작업 시 상호작용하는 것입니다.
깃은 전통적으로 명령줄을 통해 접근하지만,
더 접근하기 쉽고 편리한 인터페이스를 제공하는 다양한 도구가 있습니다.

**깃허브**와 **깃랩**은 깃 "저장소"를 온라인에 저장할 수 있게 해주는 웹 플랫폼으로,
다른 사람과 협업하기 쉽게 하고 백업을 제공합니다.

깃 도구는 로컬 컴퓨터에서 파일을 관리하는 데 사용됩니다.
그 파일은 깃허브와 같은 플랫폼에서 호스팅되는 깃 원격으로 "푸시"(업로드)됩니다.

== Gitkraken에서의 깃 튜토리얼

https://www.gitkraken.com/learn/git/tutorials[이 링크]에서
첫 4개의 튜토리얼을 확인하십시오:

- https://www.gitkraken.com/learn/git/tutorials/what-is-a-git-repository[깃 저장소란?]
- https://www.gitkraken.com/learn/git/tutorials/what-is-git-commit[깃 커밋이란?]
- https://www.gitkraken.com/learn/git/tutorials/how-to-git-commit[깃 커밋 방법]
- https://www.gitkraken.com/learn/git/tutorials/what-is-git-remote[깃 원격이란?]

이 가이드는 새티스팩토리 모드에 대해 구체적으로 수행해야 할 작업을 안내하며,
이 지식을 바탕으로 진행됩니다.
이 튜토리얼을 보면서 모드를 저장소에 넣으려고 하지 마십시오.
하지만 컴퓨터의 다른 폴더에서 실험하는 것은 자유롭게 하십시오.

물론 다른 튜토리얼을 확인할 수 있지만, 그들은 새티스팩토리 모딩과 덜 관련된 주제를 다룹니다.

== 깃 설치

핵심 깃 소프트웨어는 명령줄 도구입니다.
명령줄에서 깃을 사용할 수 있지만,
일반적으로 GUI 도구를 사용하는 것이 더 접근하기 쉽습니다.

=== 먼저 깃 CLI 설치

언리얼 에디터의 깃 통합은 깃 명령줄 인터페이스(CLI)가 설치되어야 제대로 작동합니다.
설치 프로그램을 https://git-scm.com/downloads[여기]에서 다운로드하십시오.
설치 프로그램에서 제공하는 기본 설정은 대부분의 사용자에게 적합합니다.
커밋을 위한 기본 텍스트 편집기를 선택하라는 메시지가 표시되면,
기본 Vim 외의 옵션을 선택하는 것을 고려하십시오.
이 선택은 명령줄에서 커밋하기로 결정할 경우 영향을 미칩니다.
Nano, 메모장 및 Notepad++는 편리한 대안입니다.

=== 깃 GUI 클라이언트 설치

다음 소프트웨어를 고려해 보십시오:

- https://desktop.github.com/[Github Desktop], 무료이며 초보자에게 적합합니다.
- https://www.sourcetreeapp.com/[Sourcetree], 무료지만 GitHub Desktop보다 약간 더 복잡합니다.
- https://www.gitkraken.com/[GitKraken], 비상업적 사용에 무료이며 코드가 인터넷에 공개되어야 합니다.
- https://git-fork.com/[Fork], 무료 평가판
- 추가 깃 GUI 클라이언트는 https://git-scm.com/downloads/guis[깃 웹사이트]에서 찾을 수 있습니다.

문서의 튜토리얼은 GitHub Desktop을 사용할 것이지만,
모두 유효한 선택입니다.
GitHub Desktop 설정에 대한 추가 지침이 아래에 있습니다.
다른 클라이언트를 사용하는 경우,
설정이 완료된 후 link:#_다음_단계[다음 단계 제목]으로 건너뛰어도 됩니다.

=== GitHub Desktop 설정

아마도 맞춤형 엔진 버전을 얻기 위해 깃허브에서 계정을 이미 만들었을 것입니다.
아직 만들지 않았다면 지금 만드십시오.

GitHub Desktop 설치 프로그램을 다운로드하십시오.
파일이 다운로드되면 실행하고 깃허브 계정으로 로그인하십시오.

로그인이 완료되면 "Let's get started!" 화면이 표시됩니다.
원하는 경우 튜토리얼 저장소를 만들 수 있지만,
지금은 이 프로그램을 그대로 두고 아래 단계로 진행하십시오.

== 다음 단계

==== 
시작 프로젝트를 복제하는 방법을 배우는 중에 여기에 왔다면,
문서의 해당 부분으로 돌아가려면
xref:Development/BeginnersGuide/StarterProject/StarterProjectViaClone.adoc[여기]를 클릭하십시오.
====

==== 
모드를 위한 저장소를 만들기 위해 여기에 왔다면,
그에 대한 튜토리얼로 계속 진행하려면
xref:Development/BeginnersGuide/CreateGitRepo.adoc[여기]를 클릭하십시오.
====
