= 새티스팩토리 모딩 문서

== 기초

새티스팩토리 모딩 문서 사이트에 오신 것을 환영합니다!

https://www.coffeestainstudios.com/games/[Coffee Stain Studios(CSS)]에서 제작한 공장 건설 시뮬레이션 게임인
https://www.satisfactorygame.com/[새티스팩토리(Satisfactory)] 모딩에 대한 많은 정보를 찾을 수 있습니다.
새티스팩토리의 모딩은 게임이 출시된 지 오래되었음에도 불구하고 생각보다 더 잘 확립되어 있습니다.
이미 https://ficsit.app/[600개 이상의 모드]가 출시되었으며
자신만의 모드를 만드는 방법에 대한 심층 문서를 유지하고 있습니다.

이 페이지에서는 모드 사용자와 개발자 모두를 위한 기본 정보를 제공합니다.

[TIP]
====
저희의 https://discord.ficsit.app[디스코드 서버]에 가입하여
지원받고 다른 모드 사용자 및 개발자와 대화하는 것을 추천합니다!
====

== 사용자용

모드를 사용하기 시작하고 싶다면 이 섹션이 적합할 것입니다.

=== 환영 가이드

새티스팩토리를 처음으로 모딩하는 경우,
모드를 빠르게 시작하는 방법에 대한 xref:ForUsers/Welcome.adoc[커뮤니티에 오신 것을 환영합니다] 가이드를 확인하십시오.

=== 새티스팩토리 모드 저장소 [.title-ref]#(SMR, ficsit.app, FICSIT 증강 데이터베이스)#

새티스팩토리 모드 저장소 (SMR)는 새티스팩토리를 위해 만들어진 모드의 가장 방대한 모음집입니다.
자신의 모드를 쉽게 업로드하거나 다른 사용자를 위한 안내서를 작성할 수 있습니다.
업로드된 콘텐츠는 다운로드 승인 전에 악성코드 등을 테스트합니다.
https://ficsit.app/[ficsit.app]를 방문하여 직접 확인해 보십시오!

=== 새티스팩토리 모드 관리자 [.title-ref]#(SMM)#

새티스팩토리 모드 관리자는 최종 사용자가 모드, 그 의존성 및 모드 로더를 쉽게 설치할 수 있도록 합니다.
https://ficsit.app/[SMR]에 연결되어 모든 모드를 빠르고 쉽게 설치할 수 있습니다.

====
모드 관리자를 설치하고 사용하는 방법을 배우려면
xref:ForUsers/SatisfactoryModManager.adoc[모드 관리자 사용] 페이지를 확인하십시오.
====

모드를 사용하는 것이 훨씬 더 쉬워지므로 새티스팩토리 모드 관리자를 사용하는 것을 강력히 추천합니다.
하지만 _정말_ 런처를 사용하고 싶지 않다면,
수동 설치에 대한 지침은 xref:ManualInstallDirections.adoc[여기]에서 찾을 수 있습니다.

== 개발자용

자신만의 모드를 작성하고 싶다면 이 섹션이 적합할 것입니다.

새티스팩토리 모드는 언리얼 블루프린트 또는 {cpp}로 작성할 수 있습니다.
일부 커뮤니티에서 만든 라이브러리는 JSON 파일 xref:Development/BeginnersGuide/overwriting.adoc#_contentlib[(ContentLib)]
또는 Lua xref:Development/BeginnersGuide/overwriting.adoc#_tweakit[(TweakIt)]로 모드를 작성할 수 있도록 합니다.

자신의 모드를 만들고 싶다면 C++ 모드보다 먼저 블루프린트 모드를 만드는 것을 추천합니다.
xref:Development/BeginnersGuide/index.adoc[시작 가이드]를 확인하고
저희의 https://discord.ficsit.app[디스코드]의 "채널 및 역할" 섹션에서 `Aspiring Modder` 역할을 선택하는 것을 고려해 보십시오.

모델을 만들고 싶다면 먼저 모드에 포함시키는 방법을 배우는 것이 가장 좋습니다.
`초보자 가이드`의 `건설 가능 항목` 단계를 완료한 후,
저희의 xref:Development/Modeling/index.adoc[모델링 가이드]를 확인하십시오.

=== 모드를 SMR에 업로드하기

모드(또는 최소한 첫 번째 버전)를 완료한 후에는
https://ficsit.app/[SMR]에 업로드하고 싶을 수 있습니다.
그 방법에 대한 전용 문서 페이지를 xref:UploadToSMR.adoc[여기]에서 읽어보십시오!

== 보관된 포럼

커뮤니티는 모딩 논의를 위한 Discourse 기반 포럼 웹사이트를 운영했지만,
사용량이 적어 보관되었습니다.
포럼은 https://forums.ficsit.app/[여기]에서 찾을 수 있습니다.

== 기여

문서에 기여하는 방법에 대한 정보는
https://github.com/bpforest/FICSIT-Docs#contributing[깃허브 저장소의 README]에서 찾을 수 있습니다.

== 모딩 기술

모딩이 내부적으로 어떻게 작동하는지 더 알고 싶다면 이 섹션이 당신을 위한 것입니다.

=== 새티스팩토리 모드 로더 [.title-ref]#(SML)#

새티스팩토리 모드 로더 (SML)는 모드가 게임에서 제공하는 시스템에 로드되고 서로 상호작용할 수 있도록 하는 프레임워크를 제공합니다.
또한 모드 개발을 지원하는 많은 도우미 기능을 제공합니다.
CSS가 새티스팩토리를 구성한 방식 때문에,
SML 없이도 작동하는 모드를 만드는 것이 가능하지만,
실제로는 드물게 이루어집니다.

=== 알파킷

알파킷은 Mircea와 다른 기여자들이 만든 언리얼 엔진 플러그인으로,
모드를 배포 및 배포를 위해 쉽게 조리하고 패키징할 수 있도록 합니다.
또한 게임 설치에 직접 설치할 수 있습니다.
뒤에서, 언리얼 팩과 일부 사용자 정의 코드를 사용하여 이를 수행합니다.
