= 새티스팩토리 모드 저장소에 모드 업로드하기(ficsit.app)

멋진 모드를 만들었다면, https://ficsit.app/[새티스팩토리 모드 저장소]가
다른 사람들이 당신의 모드를 찾고 사용할 수 있는 최고의 장소입니다.
SMR에 업로드된 모드는 자동으로
xref:index.adoc#_새티스팩토리_모드_관리자_smm[모드 관리자]와 함께 작동합니다.
SMR에 있는 모드는 잠재적인 보안 문제를 검사하므로,
SMR에 모드가 있다는 것은 사용자가 안전하고 신뢰할 수 있음을 의미합니다.

모드를 업로드하는 과정은 꽤 간단합니다.

== SMR에 계정 만들기

아직 계정을 만들지 않았다면,
https://ficsit.app/[SMR 홈페이지]의 오른쪽 상단에서 '로그인'을 클릭한 후,
기존 깃허브, 구글 또는 페이스북 계정으로 로그인하는 옵션을 선택할 수 있습니다.

프로필 사진과 표시 이름은 오른쪽 상단의 사용자 아이콘에서
접근할 수 있는 설정 화면에서 변경할 수 있습니다.

== 모드 페이지 만들기

사용자가 다운로드할 수 있는 모드 버전을 업로드하기 전에,
먼저 모드 페이지를 만들어야 합니다.

SMR의 '모드' 사이드바 탭에서 왼쪽 상단의 `새 모드` 를 클릭하여 시작하십시오.

=== 모드에 대한 정보

다음으로, 모드에 대한 정보를 추가할 차례입니다.

* '이름'은 모드 목록과 브라우저에 표시될 제목입니다.
* '짧은 설명'은 모드 아이콘 아래에 표시될 요약 텍스트입니다.
* '전체 설명'은 마크다운 문법을 지원하며(https://ficsit.app/help[SMR 도움말 페이지]에서 도움 얻기),
	사용자가 모든 모드 목록에서 모드를 클릭하여 볼 때 표시됩니다.
	여기에는 다음 정보를 포함하는 것이 좋습니다:
	** 모드가 게임에 추가하는 내용의 요약
	** 모드의 작동 방식을 담은 사진이나 영샹
	** 모드를 시작하는 방법(허브 마일스톤을 통해 해금? 기본적으로 활성화된 기능?)
	** 연락처 정보(가능하면 디스코드 사용자 태그, 또한 직원과 사용자가 모딩 디스코드에서 식별하는 데 도움이 됨)
	** 버그 신고 방법, 예를 들어 깃허브 이슈 페이지나 연락처 정보
	** 도움을 준 사람들에 대한 크레딧(예: 아이콘 제공, 코딩 도움)

아직 무엇을 쓸지 확신이 안 서도
걱정하지 마십시오. 나중에 이 입력란을 편집할 수 있습니다.

=== 모드 참조

이 화면에서 가장 중요한 필드 중 하나는 '모드 참조' 란입니다.
자세한 내용은
xref:Development/BeginnersGuide/SimpleMod/gameworldmodule.adoc#ModReference[모드 참조 섹션]에서 설명되어 있으며,
모드 참조는 모드의 고유한 이름입니다.
모드의 플러그인 폴더와 C++ 소스 폴더({cpp} 사용 시)는 모드 참조와 동일한 이름이어야 합니다.
모드 참조에는 특수 문자나 공백이 포함될 수 없습니다.

[WARNING]
====
**모드를 SMR에 추가한 후에는 모드 참조를 변경할 수 없습니다!**

따라서 최소 다섯 번은 정확한지 확인하십시오!
다시 xref:Development/BeginnersGuide/SimpleMod/gameworldmodule.adoc#ModReference[모드 참조 섹션]을 읽고
모드의 다른 부분이 이 동일한 값을 사용하는 이유를 정확하게 알 수 있도록 하십시오.
====

=== 아이콘 및 소스 링크

다음으로, 모드의 표시 이미지로 사용할 이미지를 업로드할 수 있습니다.
이 란을 비워두면 새티스팩토리 모딩 기어 로고가 기본값으로 사용됩니다.

소스 코드가 깃허브와 같은 사이트에 호스팅되어 있다면, 소스 코드 링크를 제공할 수도 있습니다.
소스 코드를 공개하는 것을 강력히 권장합니다.
다른 사람들이 당신의 작업에서 배우고, 다른 개발자들이 모드 호환성을 디버깅하는 데 도움이 됩니다.

이 두 란은 나중에 편집할 수 있습니다.

=== 숨겨진 모드

모드를 생성할 때 숨김으로 표시할 옵션도 있습니다.
나중에 이 옵션을 편집할 수 있습니다.

모드가 숨겨져 있으면, 주요 모드 목록이나 SMM에서 탐색할 때, 사이트 검색 시 나타나지 않습니다.
그러나 다른 사용자는 여전히 프로필 페이지를 통해 찾을 수 있으며, 직접 링크를 보낼 수 있습니다.

또한, 숨겨진 모드에 대한 업데이트는 모딩 디스코드의 `#mod-updates` 채널에 메시지를 보내지 않습니다.

=== 모드 페이지 제출

제출을 클릭하면 모드 페이지가 생성됩니다.

모드 페이지에는 모드의 모드 참조가 URL의 일부로 포함됩니다.
예를 들어, 참조가 `AreaActions` 인 모드의 페이지는 `https://ficsit.app/mod/AreaActions` 가 됩니다.

여전히 플레이어가 사용할 수 있도록 모드 버전을 업로드해야 합니다.
그때까지는 호환 가능한 버전이 없으므로 모드는 '구식'으로 표시됩니다.
이 버전 제출 과정은 다음 섹션에서 다룰 것입니다.

== 모드 패키징

버전을 업로드하기 전에,
모드의 uplugin 파일에서 편집해야 할 몇 가지 필드가 있으며,
그 후 알파킷이 모드를 번들로 묶어줍니다.

이 내용은
xref:Development/BeginnersGuide/ReleaseMod.adoc[모드 출시 페이지]에서 자세히 다루어집니다.

== 버전 업로드

`.uplugin` 을 형식화한 후,
알파킷으로 변경 사항을 포함하도록 모드를 다시 패키징했는지 확인하십시오.

모드 페이지로 이동한 후,
오른쪽 상단에서 '새 버전'을 선택하십시오.
이렇게 하면 버전 파일을 업로드하고 버전에 대한 추가 정보를 제공할 수 있는 페이지로 이동합니다.

xref:Development/BeginnersGuide/ReleaseMod.adoc#ArchivedPluginsDirectory[알파킷 배포로 모드를 패키징]할 때 생성된 출력 zip 파일을 선택하세요.
이 파일은 `모드참조.zip` 라고 불리며,
폴더의 다른 zip 파일보다 커야 합니다.
이 zip 파일에는 각 대상 플랫폼의 파일이 하나의 업로드 준비 패키지로 결합되어 있습니다.

다음으로, `변경 사항` 란에 이 버전에서 변경하거나 추가한 모든 사항의 목록을 작성하십시오.
이 변경 사항의의 처음 몇 줄은 디스코드의 #mod-updates 채널에서 버전 번호와 함께 표시되므로,
업데이트 전체에 대한 간단한 요약으로 만드는 것이 좋습니다.

[TIP]
====
이전에 모드를 숨김으로 표시하기로 결정했다면,
첫 번째 버전을 업로드하기 전에 다시 표시하는 것을 잊지 마십시오!

그렇지 않으면, 디스코드에 모드 출시 알림이 전송되지 않으며,
사이트에서 모드를 쉽게 찾을 수 없습니다.
====

[WARNING]
====
업로드하기 전에 https://ficsit.app/content-policy[ficsit.app 콘텐츠 정책]을 읽고
모드가 규칙을 준수하는지 확인하십시오.
====

마지막으로, 생성 버튼 아래의 "호환성 정보 편집" 섹션을 사용하여 모드의 호환성 정보를 업데이트하십시오.
이 정보는 사용자가 모드가 최신 버전의 게임에서 테스트되었는지 여부를 나타내기 위해 표시됩니다.
'손상됨' 또는 '고장'으로 설정하면 모드 관리자에서 경고가 표시됩니다.
문제가 발견되거나 주요 게임 업데이트가 있을 때, 당신과 신뢰할 수 있는 커뮤니티 구성원이 이 정보를 업데이트할 수 있습니다.
최신 버전의 게임에서 모드를 테스트했으므로,
"호환성 상태"를 안정적인 분기와 실험적인 분기 모두에 대해 `작동함` 으로 설정하십시오.

이제 모든 준비가 완료되었습니다. `생성` 을 누르면 업로드가 시작되며,
완료되면 모드를 사용할 수 있게 됩니다.

업로드 중 오류가 발생하면 이 화면에 표시됩니다.
xref:Development/BeginnersGuide/ReleaseMod.adoc#_smr_uplugin_validator[uplugin 검증기]가 도움이 될 수 있습니다.
해결 방법을 잘 모르겠다면 디스코드에서 도움을 요청하십시오.

== 승인 대기 중

블루프린트 전용 모드를 업로드했다면, 모드를 다운로드하고 사용할 수 있습니다!
그래도 아래 내용을 읽어보는 것이 좋습니다.

C++ 모드를 업로드했다면, 사용자가 다운로드할 수 있도록 자동 승인 과정의 승인을 기다려야 합니다.
승인 과정은 약 1~3분 정도로 일반적으로 매우 빠르며,
사용자가 SMR의 약관을 위반하거나 플레이어의 컴퓨터에 해를 끼치는 콘텐츠를 업로드하지 않도록 하기 위해 존재합니다.

그동안 모드 설명을 살펴보고 추가 정보를 추가하는 것을 강력히 권장합니다.
아래에서 더 많은 내용을 확인하십시오.

== 모드 페이지 다듬기

모드 설명은 대부분의 플레이어가 모드를 사용할지 여부를 결정할 때 보게 되는 것이므로,
조직적으로 유지하고 좋은 첫인상을 남기도록 하십시오!
모드 페이지를 보는 것이 '공장에서의 만족스러운' 경험이 되도록 노력해야 한다고 할 수 있습니다.

사용자가 모드를 시도하도록 유도하기 위해 다음 단계를 따르는 것이 좋습니다:

- 문법과 철자를 확인하십시오! 다른 사람에게 설명을 교정해 달라고 요청하는 것을 고려하십시오.
	이것은 쉬운 일이며, 올바른 문법을 사용하면 더 전문적으로 보입니다.

- 사진! 모드가 할 수 있는 것과 게임 내에서의 건물이나 기능이 어떻게 생겼는지 스크린샷을 찍으십시오.
	다시 말하지만, 긴 설명은 마크다운 문법을 지원하며, https://ficsit.app/help[도움말 페이지]에서 사용하는 방법에 대한 도움을 받을 수 있습니다.

- 도움, 문제 신고, 제안 등을 위해 연락할 수 있는 곳을 나열하십시오.
	사용자가 모드에 대한 문제를 어디에 신고하길 원하십니까?
	디스코드, 모드의 깃허브 페이지 또는 다른 곳에서?
	모드 설명에 디스코드 태그를 넣어 커뮤니티 디스코드에서 연락할 수 있도록 고려해 보십시오.
	서버에서 모드 이름을 포함하도록 별명을 변경하는 것도 고려하십시오.

- 사용자에게 불명확할 수 있는 모드의 개념이나 기능을 설명하십시오.
	모드를 사용하는 방법에 대한 문서를 작성하지 않거나 https://ficsit.app/guides[가이드]를 작성하지 않는 한,
	플레이어는 모드의 모든 놀라운 새 콘텐츠를 사용하는 방법을 파악하는 데 어려움을 겪을 수 있습니다.

- 모드의 기능과 게임 내에서 사용하는 방법을 나열하십시오.
	어떤 티어에서 콘텐츠가 잠금 해제되는지 나열하는 것을 고려하십시오.

- 아이디어, 모델 등을 기여한 다른 사용자에게 이름 및/또는 링크로 크레딧을 부여하십시오.

== 업데이트 업로드

새 버전을 업로드할 때,
`Version`, `VersionName`, `SemVersion` 란을
`<모드 참조>.uplugin` 에서 적절히 증가시키십시오.
모드의 SML에 대한 의존성에서 지정된 버전도 최신 SML 배포로 변경하고,
모드가 지원하는 최신 게임 버전으로 GameVersion을 변경해야 합니다.
알파킷 배포의 경고 버튼이 이를 도와줄 것입니다.

이러한 편집은 알파킷 도우미를 통해 편집기에서 수행하거나
텍스트 편집기에서 `.uplugin` 파일을 직접 편집하여 수행할 수 있습니다.

게임 업데이트로 인해 '고장' 또는 '손상됨'으로 표시된 경우,
모드의 호환성 정보를 업데이트하는 것을 잊지 마십시오!
