= 제작

새티스팩토리의 제작 시스템은 비교적 간단하며,
자신의 제작법을 추가하기 쉽습니다.

== 제작법 [.title-ref]#(FGRecipe)#

작업대, 빌드건 또는 기타 기계에 대한 제작법을 설명하는 것은
네이티브 `FGRecipe` 클래스를 사용하여 이루어집니다.
제작법을 통해 필요한 아이템과 수량을 설명하여
주어진 아이템을 주어진 수량으로 얻을 수 있습니다.

빌드건 제작법도 `FGRecipe` 로 설명되므로,
빌드건에 새로운 건물을 추가하려면
적절한 기본값을 가진 새로운 `FGRecipe` 클래스를 생성하고
제작법을 등록해야 합니다.

새티스팩토리는 모든 제작법을 등록하고 저장하는 제작법 관리자를 사용합니다.
일반 작업대 제작법을 추가하든 제련 제작법을 추가하든,
원하는 디스크립터와 수량으로 제작법을 생성한 후
관리자에 등록하도록 하십시오.
기계는 이 관리자에서 정보를 가져와
플레이어가 제작할 수 있는 것과 그렇지 않은 것을 적절히 선택할 수 있도록 합니다.
이를 결정하기 위해, 기계가 이 제작법을 제작할 수 있는지 확인하려면
"`Crafter`" 인터페이스를 구현하는 객체 유형을 전달해야 합니다.

* {blank}
+
M Display Name::
  제작법의 이름을 정의하려면 이 옵션을 체크하고 이름을 입력하십시오.
* {blank}
+
M Ingredients::
  각 제작 구성 요소의 정보를 포함하는 구조체의 배열입니다.
  배열은 제작법의 입력 아이템을 형성합니다.
* {blank}
+
M Manufacturing Duration::
  기계가 이 제작법을 처리하는 데 걸리는 시간을 결정합니다.
* {blank}
+
M Manual Manufacturing Multiplier::
  기계와 제작대에서 동일한 제작법을 사용하려면,
  이 값을 사용하여 제작대에서 이 제작법의 제작 시간이 얼마나 더 걸릴지를 정의할 수 있습니다.
* {blank}
+
M Produced In::
  제작법을 사용할 수 있는 기계를 선택합니다.
* {blank}
+
M Product::
  제작법의 출력 아이템 유형과 수량에 대한 정보를 포함하는 구조체의 배열입니다.
