= 인벤토리 및 아이템

[NOTE]
====
이 페이지는 포괄적이지 않습니다.
추가 컨텍스트 및 도움말 기능은 `FGIinventoryComponent.h` 및 `FGIinventoryLibrary.h` 의 댓글을 확인하십시오.
====

== 아이템 디스크립터 [.title-ref]#(`UFGItemDescriptor`)#

네이티브 `AFGItemDescriptor` 클래스는 아이템과 유사한
게임 개념의 속성을 포함합니다.
특히, 이는 UFGBuildDescriptor(건물) 및
UFGFactoryCustomizationDescriptor(커스터마이징 패턴)와 같은 것들의 기본 클래스이며,
일반적인 의미의 '아이템'이 아니며,
모든 사용 가능한 UFGItemDescriptor 속성을 사용하지 않습니다.

== 인벤토리 아이템 [.title-ref]#(`FInventoryItem`)#

아이템 디스크립터와 관련된 아이템 상태(모든 종류의 액터)의 단일 "인스턴스"를 나타냅니다.
일반적으로 벨트와 같이 인벤토리 이외의 품목을 언급할 때 사용됩니다.

대부분의 아이템에는 상태가 없으며, 게임의 제작법 체계는 아이템 상태를 무시합니다.
장비 아이템은 탄약/연료 수준, 사용자 설정 및 기타 지속적인 데이터를 저장하기 위해 아이템 상태를 사용합니다.

== 아이템 수량 [.title-ref]#(`FItemAmount`)#

이 구조체는 아이템 디스크립터와 상태 없이 아이템 수량을 연결합니다.
저장 방식에 관계없이 아이템의 양을 나타내는 데 유용합니다.
주로 제작법과 도면 비용에서 재료/제품을 정의하는 데 사용됩니다.

아이템 상태 데이터를 잃지 않도록 인벤토리 묶음으로 변환하거나 인벤토리 묶음에서 변환하는 데 주의하십시오.

== 인벤토리 묶음 [.title-ref]#(`FItemStack`)#

이것은 아이템 수량의 형제이지만 이번에는 아이템과 수량을 보유합니다.
즉, 이번에는 실제로 게임 내 아이템과 그 수량에 대한 정보를 보유하는 데 사용됩니다.
예를 들어, 한 플레이어의 인벤토리 슬롯에 몇 개의 아이템이 있는지에 대한 정보입니다.

아이템 상태 데이터를 잃지 않도록 아이템 수량으로/에서 변환하는 데 주의하십시오.

== 인벤토리 요소 [.title-ref]#(`UFGInventoryComponent`)#

이것은 `USceneComponent` 로, 여러 아이템 묶음을 동시에 보유할 수 있는 인벤토리를 액터에 부착하는 데 사용됩니다. 이는 플레이어뿐만 아니라 아이템이 내부에 있는 경우 거의 항상 사용됩니다.
즉, 아이템으로 가득 찬 컨테이너처럼 생각할 수 있습니다.
