= 인벤토리 및 아이템

이 페이지는 인벤토리 자체를 설명할 뿐만 아니라,
그에 의해 사용되는 모든 것에 대해서도 설명합니다.

== 아이템 디스크립터 [.title-ref]#(`UFGItemDescriptor`)#

네이티브 `AFGItemDescriptor` 클래스는 아이템과 유사한
게임 개념의 속성을 포함합니다.
특히, 이는 UFGBuildDescriptor(건물) 및
UFGFactoryCustomizationDescriptor(커스터마이징 패턴)와 같은 것들의 기본 클래스이며,
일반적인 의미의 '아이템'이 아니며,
모든 사용 가능한 UFGItemDescriptor 속성을 사용하지 않습니다.

== 아이템 [.title-ref]#(`FInventoryItem`)#

이 구조체는 아이템에 대한 정보(아이템 디스크립터에 대한 클래스 포인터)와 연결된 아이템 상태(모든 종류의 액터)를 포함합니다.

== 아이템 수량 [.title-ref]#(`FItemAmount`)#

이 구조체는 아이템 디스크립터와 상태 없이 아이템 수량을 연결합니다.
즉, 이 구조체는 게임 내 아이템의 표현 정보를 보유하는 데 사용되지 않습니다.
대신, 이는 예를 들어 제작법에서 어떤 종류의 아이템을 얼마나 가져와야 하는지를 정의하는 데 사용됩니다.

== 아이템 묶음 [.title-ref]#(`FItemStack`)#

이것은 아이템 수량의 형제이지만 이번에는 아이템과 수량을 보유합니다.
즉, 이번에는 실제로 게임 내 아이템과 그 수량에 대한 정보를 보유하는 데 사용됩니다.
예를 들어, 한 플레이어의 인벤토리 슬롯에 몇 개의 아이템이 있는지에 대한 정보입니다.

== 인벤토리 요소 [.title-ref]#(`UFGInventoryComponent`)#

이것은 `USceneComponent` 로, 여러 아이템 스택을 동시에 보유할 수 있는 인벤토리를 액터에 부착하는 데 사용됩니다. 이는 플레이어뿐만 아니라 아이템이 내부에 있는 경우 거의 항상 사용됩니다.
즉, 아이템으로 가득 찬 컨테이너처럼 생각할 수 있습니다.