= 자원 싱크

기본적으로, 모드된 아이템은 쿠폰 포인트를 얻기 위한
관련 점수 값이 없으므로 A.W.E.S.O.M.E. 싱크에 공급할 수 없습니다.

모드의 아이템이 공급 가능하도록 하려면,
공급 시 제공하는 포인트 수를 지정해야 합니다.

SML은 FGItemDescriptors 목록을 쉽게 로드하고
데이터 테이블을 통해 포인트 값을 할당할 수 있는 기능을 제공합니다.
게임 월드 (하위) 모듈당 하나의 테이블만 존재할 수 있습니다.

== 데이터 테이블

시작하려면, 에디터의 콘텐츠 브라우저 창으로 가서 새로운 데이터 테이블 애셋을 추가합니다(기타 범주의 고급 자산입니다).
행 구조를 선택하라는 메시지가 표시되면, 드롭다운에서 `Resource Sink Points Data` 를 선택합니다.
"Points_모드이름" 또는 비슷한 이름을 사용해 나중에 쉽게 찾을 수 있도록 합니다.

공급 가능한 각 아이템에 대해 데이터 테이블에 행을 생성해야 합니다.
`Row Name` 은 중요하지 않으며, `Item Class`는 아이템의 FGItemDescriptor여야 하고,
`Points` 열은 공급 시 해당 아이템의 점수를 나타냅니다.
각 기본 아이템이 얼마나 많은 점수를 제공하는지 비교하려면
https://satisfactory.wiki.gg/AWESOME_Sink#Points_generated_per_item[새티스팩토리 위키]를 참고하십시오.
아이템의 구성 요소 합계보다 더 많은 포인트를 제공하여
원자재를 단순히 공급하는 것보다 제작 및 공급을 장려하는 것이 좋습니다.
https://satisfactory.wiki.gg/AWESOME_Sink#Recipe_point_improvement_ratios[여기]에서 비교를 위한 다양한 기본 제작법의 "이득 점수"를 확인할 수 있습니다.

추가 열인 `Overridden Resource Sink Points` 가 있습니다. 이 값은 항상 -1로 설정해야 합니다.
CSS는 스크립트를 사용하여 점수 값을 자동으로 계산하며,
이 열을 사용하여 생성된 값을 수동으로 재정의합니다.
우리는 수동으로 값을 지정하고 있으므로 이 열은 필요하지 않습니다.
-1이 아닌 값을 지정하면 게임은 두 입력란 중
더 높은 점수 값을 선택합니다.

== 데이터 테이블 등록

이제 새티스팩토리에 데이터 테이블의 내용을 불러오도록 지시해야 합니다.
다행히도 SML이 이를 도와줄 수 있습니다. xref:Development/ModLoader/ModModules.adoc#_game_world_module_ugameworldmodule[게임 월드 모듈]을 사용하여
방금 생성한 데이터 테이블을 기본 탭(고급 하위 섹션)에서
`M Resource Sink Item Points Data Table` 변수에 설정하십시오.
SML은 내용을 읽고 자원 싱크 시스템에 추가합니다.

== 기본 포인트 값 재정의

모드의 자원 공급 데이터 테이블에 새로운 점수 값으로 아이템을 나열하여 기본 게임에서 지정한 점수 값을 재정의할 수 있습니다.

여러 모드가 점수 값을 지정하는 경우, 마지막으로 로드된 모드의 점수 값이 게임에서 사용됩니다.
