= 도면

도면은 커피 스테인 스튜디오의 연구 시스템에 대한 답변입니다.
도면은 연구 마일스톤의 요구 사항, 시각적 요소 및 보상에 대한 정보를 담고 있습니다.

게임 내에서 기술적 진행이 이루어지는 모든 것이 도면입니다.
M.A.M.에서의 분석, 허브 업그레이드, A.W.E.S.O.M.E. 상점 구매, 우주 엘리베이터의 티어 단계까지 모든 것이 도면입니다.

도면의 요구 사항(아이템 비용, 전제 조건, 시간)은 도면에 직접 설정되지만, 보상은 이른바 "해금"에 의해 정의됩니다.
이 잠금 해제는 새로운 제작법, 건물, 인벤토리 슬롯 등 무엇이든 될 수 있습니다.

모드에서 맞춤 마일스톤이나 M.A.M. 연구를 구현하려면 도면을 만들어야 합니다.

== FGUnlock (`UFGUnlock`)
이 클래스는 도면이 해금될 때 얻는 보상을 설명합니다.
제작법이나 다른 도면, 인벤토리 슬롯 등 무엇이든 될 수 있습니다.

CSS는 이미 이러한 것들을 기본 클래스 형태로 제공하지만, 도면에서 더 쉽고 나은 사용을 가능하게 하는 블루ㅍ린트 래퍼 클래스도 제공하여,
CSS에서 파생된 많은 맞춤 해금을 만들 필요 없이 기본 값을 설정할 수 있습니다.
대신 블루프린트 래퍼를 사용하면 도면에서 직접 이러한 기본 값을 정의할 수 있습니다.

사용할 수 있는 해금 목록과 그 블루프린트 래퍼는 다음과 같습니다:

[cols="1,4a"]
|===
|블루프린트 래퍼 |기능 설명

|UnlockArmEquipmentSlot
|플레이어에게 추가 팔 장비 슬롯을 제공합니다. 6개 이상의 슬롯이 있으면 인벤토리 화면이 이상하게 보이지만 여전히 작동합니다.

|UnlockBuildEfficiency
|플레이어가 기계 UI에서 초당 생산/소비되는 아이템 수에 대한 계산된 값을 볼 수 있게 합니다. 기본 게임은 이미 초기 티어 중 하나에서 이를 수행합니다.

|UnlockBuildOverclock
|플레이어가 기계의 오버클럭/언더클럭 설정에 접근할 수 있게 합니다. 기본 게임은 이미 동력 조각 연구로 이를 수행합니다.

|UnlockGiveItem
|도면이 해금될 때 플레이어에게 아이템을 제공합니다.

|UnlockInventorySlot
|플레이어에게 추가 인벤토리 슬롯을 제공합니다.

|UnlockMap
|플레이어가 게임 내 미니맵 화면에 접근할 수 있게 합니다. 기본 게임은 이미 지도 연구로 이를 수행합니다.

|UnlockRecipe
|플레이어가 사용할 수 있는 제작 또는 건물 제작법을 해금합니다.

|UnlockScannableResource
|자원 탐색기에 자원을 추가합니다.

|UnlockSchematic
|이 도면이 완료되면 다른 FGSchematic을 잠금 해제합니다.

|UnlockSubsystem
| 
|===

== FGSchematic (`UFGSchematic`)

FGSchematic 클래스는 연구 마일스톤에 대한 일반 정보를 담고 있습니다.
이 연구 마일스톤은 M.A.M. 연구 노드, 허브 업그레이드, 우주 엘리베이터 티어 등 무엇이든 될 수 있습니다.

* {blank}
+
M Type::
  도면의 유형으로, 튜토리얼 시스템, M.A.M., A.W.E.S.O.M.E. 상점, 마일스톤
  등의 일부인지 여부를 결정합니다.
* {blank}
+
M Display Name::
  플레이어에게 표시되는 도면의 게임 내 이름입니다.
* {blank}
+
M Schematic Category::
  이 도면이 그룹화되는 범주를 정의합니다.
* {blank}
+
M Sub Categories::
  배열로, 도면이 분류될 하위 그룹을 정의합니다.
* {blank}
+
M Tech Tier::
  도면이 허브에서 나타날 티어를 결정합니다.
  0은 '튜토리얼' 동안이며, 발사 버튼 대신 허브 업그레이드 버튼이 표시됩니다.
* {blank}
+
M Time to Complete::
  이 도면을 구매한 후
  화물선이 떠나는 시간(초) 또는
  M.A.M.이 연구 노드를 처리하는 데 걸리는 시간을 정의합니다.
* {blank}
M Schematic Icon::
  허브 또는 M.A.M.에서 도면에 표시되는 아이콘입니다.
* {blank}
+
M Cost::
  도면을 구매하는 데 필요한 아이템 수량의 배열입니다.
* {blank}
+
M Unlocks::
  이 도면을 해금할 때 플레이어가 받을 보상을 포함하는 배열입니다.
  이는 link:#_fgunlock_ufgunlock[FGUnlock]의 배열입니다.
* {blank}
+
M Schematic Dependencies::
  이 배열은 다른 도면이 구매될 때까지(`BPSchematicPurchasedDependency`)
  도면이 숨겨지도록 하거나 특정 아이템이 수집될
  때까지(`BPItemPickedUpDependency`) 숨겨지도록 합니다.
{blank} +
{blank} +
  배열의 모든 항목은 도면이 표시되기 위해 충족되어야 합니다.
{blank} +
{blank} +
  두 가지 모두 여러 도면/아이템을 선택할 수 있습니다.
  Require All을 활성화하면 해당 그룹의 모든
  도면/아이템이 구매/발견되어야 도면이 표시됩니다.
  Require All이 체크되지 않으면 하나만 필요합니다.
  아이템 획득 의존성으로 사용되는 아이템은 해당 아이템 디스크립터에 `HasPickedUpItem` 플래그가 설정되어 있어야 획득이 추적되고 이 요구 사항이 작동합니다.
* {blank}
+
M Include In Builds::
  이 도면이 불러오고 구워질 수 있는 빌드를 정의합니다.
  아마도 커피 스테인이 테스트를 위해 만든 개발자 마일스톤이 메인 게임과 함께 배포되지 않도록 하기 위해 사용하는 것입니다.
  이를 `PublicBuilds` 로 설정하는 것이 좋습니다. 그렇지 않으면 플레이어가 모드를 사용할 수 없을 것입니다.
