= 새티스팩토리 모딩 커뮤니티에 오신 것을 환영합니다

새티스팩토리 모딩 커뮤니티와 ficsit.app 모드 저장소에 오신 것을 환영합니다!

아래에는 모드를 찾고 설치하는 방법과 모드에 대한 도움을 받는 방법이 설명되어 있습니다.

== 자주 묻는 질문

질문이 있다면, 그 질문은 꽤 좋은 확률로
xref:faq.adoc[자주 묻는 질문] 페이지에 답변이 있을 것입니다.

거기에서 답변이 없거나 불명확한 점이 있다면,
https://discord.ficsit.app[디스코드 서버]에서 질문해 주십시오.

== 모드 관리자 설치

모드를 사용하려면 새티스팩토리 모드 관리자(SMM)를 설치해야 합니다.
이 프로그램은 설치 시 모든 구성을 처리하며,
모드를 작동시키고 게임에 넣는 가장 좋은 방법입니다.
모드 관리자를 설치하고 사용하는 방법은
xref:ForUsers/SatisfactoryModManager.adoc[모드 관리자 사용] 페이지에서 확인할 수 있습니다.

== 새로운 모드 찾아보기

모든 새티스팩토리 모드는 https://ficsit.app/[새티스팩토리 모드 저장소]에 업로드됩니다.
하지만 목록을 살펴보는 방법은 여러 가지가 있습니다.

=== 모드 관리자에서

모드 관리자를 통해 모드 목록을 직접 탐색할 수 있습니다!
우측 상단 필터가 "호환됨"으로 설정되어 있는지 확인하십시오.
스크롤하여 옵션을 탐색하거나 검색창을 사용하여 특정 모드를 검색할 수 있습니다.
모드를 클릭하면 세부 패널에서 모드 페이지가 열립니다.

// TODO tags tag search in SMM

=== ficsit.app에서

ficsit.app 웹사이트에서 모드를 탐색하는 것을 선호한다면,
거기에서도 모드를 쉽게 설치할 수 있습니다.

모드 페이지에 들어가면 오른쪽 상단의 '버전' 버튼을 클릭한 후,
"최신 버전" 섹션에서 다운로드 화살표 아이콘을 클릭하여 모드를 모드 관리자를 통해 설치하십시오.
이렇게 하면 웹사이트가 설치된 모드 관리자와 통신할 수 있도록 허용하라는 메시지가 표시되며,
모드를 설치하는 작업을 처리합니다.

== 추천 모드

개발자가 의도한 대로 새티스팩토리를 경험하기 위해,
모드 없이 게임을 잠시 플레이하며 최소한
https://satisfactory.wiki.gg/wiki/Milestones#Tier_6[허브의 6단계]를 잠금 해제할 것을 권장합니다.
하지만 여기 계신다면, 기본 게임만 플레이할 생각은 아닐 것입니다!
기본 게임의 느낌과 균형을 유지하고 싶다면,
xref:ForUsers/Tags.adoc[품질 향상 모드]와 태그가 붙은 모드를 확인해 보십시오.

새로운 경험을 원하신다면, 모드 저장소를 확인해 보십시오!
선택할 수 있는 옵션이 많으며,
xref:ForUsers/Tags.adoc[태그로 필터링]하여 플레이 스타일에 맞는 모드를 찾을 수 있습니다.

[id="GettingInfoAboutMods"]
== 모드에 대한 정보 얻기

모드 개발자가 자신의 모드를 사용하는 방법을 알려주는 것은 그들의 책임입니다.
ficsit.app의 모드 페이지에서 문서를 확인하십시오.

일반적으로 대부분의 모드는 사용하기 전에 허브나 M.A.M.에서 무언가를 잠금 해제해야 합니다.
모드는 메인 메뉴의 '모드' 탭에서 구성할 수 있으며,
게임 중에는 일시 정지 메뉴의 '모드 구성' 탭에서 구성할 수 있습니다.

일부 모드는 문서 사이트나 디스코드 가입 링크와 같은 지원 링크를 제공할 수 있습니다.
게임 내 모드 메뉴에서 "지원 받기" 버튼을 통해 이 링크에 접근할 수 있습니다.
해당 모드에서 제공하는 링크가 없으면 버튼이 나타나지 않습니다.
같은 링크가 ficsit.app의 모드 페이지에도 있을 가능성이 높습니다.

== 나만의 모드 만들기

자세한 정보는
xref:index.adoc#_for_developers[홈페이지의 이 섹션]을 확인하십시오.
