= SMLEditor

**SML Editor**는 시작 프로젝트와 함께 배포되는 에디터 전용 '모드'입니다.
모드 개발자를 위한 여러 유용한 유틸리티를 포함하고 있습니다.
모드에 패키징될 의도가 없기 때문에 알파킷 메뉴에서 의도적으로 제외되었습니다.

이 문서 섹션에서는 모드에 포함된 각 도구를 간략하게 설명합니다.

== 연구 트리 편집기

위치: `/SMLEditor/ResearchTree/AssetAction_ResearchTreeHelper`

M.A.M. 연구 트리를 시각적 인터페이스를 통해 보고 생성하는 유틸리티입니다.
자세한 내용은 xref:Development/EditorTools/SMLEditor/ResearchTreeEditor.adoc[전용 문서 페이지]를 참고하십시오.

이를 사용하려면 콘텐츠 브라우저에서 유틸리티 위젯을 실행하거나
원하는 연구 트리를 우클릭 후
`Scripted Asset Actions` > ``SMLEditor: Open Research Tree Editor``를 실행하십시오.

== 모드 구성 미리보기

위치: `/SMLEditor/MenuPreview/SML_MenuPreviewWidget`

에디터에서 xref:Development/ModLoader/Configuration.adoc[모드 구성]을 미리 볼 수 있게 해줍니다.
이를 사용하려면 모드 구성 애셋을 우클릭 후
`Scripted Asset Actions` > ``SMLEditor: Preview Mod Configuration in Editor``를 실행하십시오.

에디터 위젯 또는 애셋 작업 유틸리티의 우클릭 메뉴에서 실행할 수도 있습니다.

// cspell:ignore Reparenter

== 대량 애셋 재부모기

위치: `/SMLEditor/Utils/AssetAction_MassReparent`

여러 애셋의 부모 클래스를 한 번에 쉽게 변경할 수 있습니다.

이를 사용하려면 먼저 에디터가 충돌할 경우를 대비해 모든 것을 저장해야 합니다.
그런 다음 하나 이상의 애셋을 선택하고 하나를 우클릭 후
`Scripted Asset Actions` > ``SMLEditor: Reparent Selected Assets``를 실행하십시오.
팝업에서 새 부모 클래스를 선택하고 저장했음을 확인한 후 "OK"를 클릭하십시오.

== 에디터 내 테스트 예제

위치: `/SMLEditor/InEditorTestingExample/`

이 맞춤 레벨과 위젯은 에디터 내에서 기본 액터 및 위젯 기능을 테스트하는 방법을 보여줍니다.
에디터에서 테스트하면 게임을 다시 시작하는 데 드는 시간을 절약할 수 있습니다.
테스트하는 기능이 게임 시스템에 의존하지 않는 한 가능합니다.
대부분의 게임 시스템은 에디터에서 제대로 작동하지 않으며 호출 시 에디터가 충돌할 수 있습니다.
xref:Development/BeginnersGuide/StarterProjectStructure.adoc#PlaceholderSystem[프로젝트의 대부분의 게임 코드는 스텁입니다].

이를 열려면 `SMLEditor_Testing` 레벨 애셋을 열고 에디터 툴바에서 "플레이" 버튼을 클릭하십시오.
레벨의 블루프린트 코드를 보려면,
재생 버튼 왼쪽의 3박스 버튼("세계 블루프린트 목록")을 클릭하고
"레벨 블루프린트 열기"를 선택하십시오.

== ADA 메시지 추출기

위치: `/SMLEditor/AdaMessages/AdaMessageExtractor`

이 유틸리티는 프로젝트의 모든 FGMessage 애셋을 로드하고 이들에 대한 데이터를 하나의 문자열로 컴파일합니다.
ADA와 외계인이 대화할 때 사용하는 말하기 패턴을 보기 위해
많은 개별 메시지 애셋을 찾아다닐 필요 없이 유용할 수 있습니다.

이를 사용하려면 에디터 유틸리티 위젯을 우클릭 후 "에디터 유틸리티 위젯 실행"을 선택하십시오.

////

== 스마트 제작법 뷰어

위치: `/SMLEditor/RecipeEditor/`

자세한 내용은 xref:Development/EditorTools/SMLEditor/RecipeEditor.adoc[전용 페이지]를 참고하십시오.

////
