= SMLEditor

**SML Editor**는 시작 프로젝트와 함께 배포되는 에디터 전용 '모드'입니다.
모드 개발자를 위한 여러 유용한 유틸리티를 포함하고 있습니다.
모드에 패키징될 의도가 없기 때문에 알파킷 메뉴에서 의도적으로 제외되었습니다.

이 문서 섹션에서는 모드에 포함된 각 도구를 간략하게 설명합니다.

[id="ResearchTreeEditor"]
== 연구 트리 편집기

위치: `/SMLEditor/ResearchTree/AssetAction_ResearchTreeHelper`

M.A.M. 연구 트리를 시각적 인터페이스를 통해 보고 생성하는 유틸리티입니다.
자세한 내용은 xref:Development/EditorTools/SMLEditor/ResearchTreeEditor.adoc[전용 문서 페이지]를 참고하십시오.

이를 사용하려면 콘텐츠 브라우저에서 유틸리티 위젯을 실행하거나
원하는 연구 트리를 우클릭 후
`Scripted Asset Actions` > ``SMLEditor: Open Research Tree Editor``를 실행하십시오.

[id="ModConfigurationPreviewer"]
== 모드 구성 미리보기

위치: `/SMLEditor/MenuPreview/SML_MenuPreviewWidget`

에디터에서 xref:Development/ModLoader/Configuration.adoc[모드 구성]을 미리 볼 수 있게 해줍니다.
이를 사용하려면 모드 구성 애셋을 우클릭 후
`Scripted Asset Actions` > ``SMLEditor: Preview Mod Configuration in Editor``를 실행하십시오.

에디터 위젯 또는 애셋 작업 유틸리티의 우클릭 메뉴에서 실행할 수도 있습니다.

[id="MassAssetReparenter"]
== 대량 애셋 재부모기

위치: `/SMLEditor/Utils/AssetAction_MassReparent`

여러 애셋의 부모 클래스를 한 번에 쉽게 변경할 수 있습니다.

이를 사용하려면 먼저 에디터가 충돌할 경우를 대비해 모든 것을 저장해야 합니다.
그런 다음 하나 이상의 애셋을 선택하고 하나를 우클릭 후
`Scripted Asset Actions` > ``SMLEditor: Reparent Selected Assets``를 실행하십시오.
팝업에서 새 부모 클래스를 선택하고 저장했음을 확인한 후 "OK"를 클릭하십시오.

[id="InEditorTestingExample"]
== 에디터 내 테스트 예제

위치: `/SMLEditor/InEditorTestingExample/`

이 맞춤 레벨과 위젯은 에디터 내에서 기본 액터 및 위젯 기능을 테스트하는 방법을 보여줍니다.
에디터에서 테스트하면 게임을 다시 시작하는 데 드는 시간을 절약할 수 있습니다.
테스트하는 기능이 게임 시스템에 의존하지 않는 한 가능합니다.
대부분의 게임 시스템은 에디터에서 제대로 작동하지 않으며 호출 시 에디터가 충돌할 수 있습니다.
xref:Development/BeginnersGuide/StarterProjectStructure.adoc#PlaceholderSystem[프로젝트의 대부분의 게임 코드는 스텁입니다].

이를 열려면 `SMLEditor_Testing` 레벨 애셋을 열고 에디터 툴바에서 "플레이" 버튼을 클릭하십시오.
레벨의 블루프린트 코드를 보려면,
재생 버튼 왼쪽의 3박스 버튼("세계 블루프린트 목록")을 클릭하고
``레벨 블루프린트 열기``를 선택하십시오.

[id="AdaMessageExtractor"]
== ADA 메시지 추출기

위치: `/SMLEditor/AdaMessages/AdaMessageExtractor`

이 유틸리티는 프로젝트의 모든 FGMessage 애셋을 로드하고 이들에 대한 데이터를 하나의 문자열로 컴파일합니다.
ADA와 외계인이 대화할 때 사용하는 말하기 패턴을 보기 위해
많은 개별 메시지 애셋을 찾아다닐 필요 없이 유용할 수 있습니다.

이를 사용하려면 에디터 유틸리티 위젯을 우클릭 후 ``에디터 유틸리티 위젯 실행``을 선택하십시오.

[id="RecipeLinter"]
== 제작법 린터

``/SMLEditor/Recipe/RecipeLinter/AssetAction_CheckWithRecipeLinter``에 위치해 있습니다.

이 유틸리티는 제작법에서 발생할 수 있는 잠재적인 문제나 누락된 부분을 확인하는 데 도움을 줍니다.
현재 포함된 검사 항목은 다음과 같습니다(이에 국한되지 않음):

- 재료/생산품의 수량과 최대 묶음량으로 인한 기계 정지 또는 멈춤 현상(소머슬룹 적용 시 포함)
- 제작법에서 유체 수량을 1000배로 곱하는 것을 잊은 경우
- 생산 설비가 지원하는 것보다 더 많은 유체/고체 포트를 사용하는 경우
- 빌드건 제작법에 여러 생산품이 포함된 경우
- 수동 제작법에 유체가 포함된 경우
- 생산자가 없는 제작법

사용하려면 FGRecipe를 상속받은 하나 이상의 애셋을 선택한 후,
하나를 우클릭하여
`Scripted Asset Actions` > ``SMLEditor: Lint Recipes for Common Mistakes``를 실행하십시오.
결과는 에디터의 출력 로그 탭에 표시됩니다.

새로운 검사 항목은 ``URecipeLintingCheckInterface``를 구현하는 클래스를 생성하고
`AssetAction_CheckWithRecipeLinter` 애셋의 `RecipeChecks` 배열에 추가하여 만들 수 있습니다.

////

[id="RecipeViewer"]
== 스마트 제작법 뷰어

위치: `/SMLEditor/RecipeEditor/`

자세한 내용은 xref:Development/EditorTools/SMLEditor/RecipeEditor.adoc[전용 페이지]를 참고하십시오.

////
