= 시작 프로젝트

SML 개발 팀은 새티스팩토리 모드 로더,
기본 게임 콘텐츠를 위한 플레이스홀더 애셋,
유용한 개발자 플러그인이 사전 설치된
언리얼 프로젝트를 제공합니다.

이 '시작 프로젝트'에서는 파일을 분리하면서
원하는 만큼의 모드를 개발할 수 있으며,
이 과정은 나중에 문서에서 다룰 예정입니다.

먼저, 컴퓨터에서 시작 프로젝트 파일을 저장할 위치를 결정해 보겠습니다.

== 저장 위치 선정하기

시작 프로젝트 폴더는 모딩 작업 공간이 될 것이며,
어떤 종류의 모드를 만드느냐에 따라 상당한 파일 크기로 커질 수 있습니다.
따라서 나중에 찾을 수 있도록 편리한 곳에서 폴더를 추출해야 합니다.

다음 위치에 프로젝트를 배치하지 **마십시오**:

* ❌ 다운로드 폴더
    ** Windows는 시스템 설정에 따라 때때로 파일을 지워 이 폴더를 청소합니다.
* ❌ 클라우드 연동 폴더
    ** Dropbox, Google 드라이브, OneDrive와 같은 클라우드 연동 서비스는 프로젝트 파일을 손상시킬 수 있습니다.
* ❌ 문서 폴더
    ** 일부 클라우드 연동 서비스는 말 없이 문서 폴더를 자동으로 동기화할 수 있습니다.
* ❌ 혼잡한 폴더
    ** 언리얼 프로젝트를 패킹할 때 일부 파일 이름이 길어질 수 있으므로, Windows가 긴 경로를 제대로 처리하지 못하기 때문에 깊이 중첩된 위치가 기괴한 문제를 일으킬 수 있습니다.
* ❌ 이름에 특수/국제 문자가 있는 폴더
    ** 언리얼과 Windows는 파일 및 폴더 이름의 유니 코드 문자를 쉽게 혼동합니다.

다음과 같은 조건에 두는 것을 **고려하십시오**:

* ✔️ 드라이브의 루트 경로와 가깝게 (예를 들어 `C:\Modding\Satisfactory\`)
    ** 이는 긴 경로 문제를 피하고 컴퓨터의 사용자 이름이 모드와 함께 배포되는 것을 막습니다.
* ✔️ SSD 안에
    ** 프로젝트가 SSD에 있다고 가정하면 대부분의 모딩 작업이 훨씬 더 빠르게 실행됩니다.
* ✔️ 보조 드라이브에
    ** 이렇게 하면 기본 드라이브가 모딩 파일로 채워지지 않도록 도와줍니다.

프로젝트를 어디에 배치할지 결정한 후 다음 단계로 이동합니다.

== 시작 프로젝트 얻기

시작 프로젝트를 얻는 방법에는 두 가지가 있습니다.
아래 세부 사항과 편안한 내용을 기준으로 하나를 선택하십시오.

=== 옵션 1: Git Clone

버전 관리 소프트웨어(예: Git)에 익숙하다면,
나중에 게임이 업데이트될 때 파일을 업데이트하는 과정을
획기적으로 간소화할 수 있도록 저장소를 복제하는 것을 권장합니다.

버전 관리에 익숙하지 않다면
지금이 바로 xref:Development/BeginnersGuide/LearnGit.adoc[배울 수 있는 좋은 기회]입니다!
버전 관리 소프트웨어(VCS)를 사용하는 것은 개발자에게 훌륭한 기술이며
향후 프로젝트 업데이트에 큰 도움이 될 뿐만 아니라
깃허브와 같은 호스팅 웹사이트에 업로드하면 모드 소스를 잃지 않도록 보호할 수 있습니다.

====
xref:Development/BeginnersGuide/StarterProject/StarterProjectViaClone.adoc[Git Clone 방법 사용 ➡]
====

=== 옵션 2: Zip 파일 다운로드

버전 관리에 익숙하지 않고 그냥 모딩을 시작하고 싶다면,
새티스팩토리 모딩 깃허브에서
시작 프로젝트의 zip 파일을 다운로드할 수 있습니다.

====
xref:Development/BeginnersGuide/StarterProject/StarterProjectViaZip.adoc[Zip 파일 다운로드 방법 사용 ➡]
====
