= Zip 파일 다운로드

시작 프로젝트 저장소의 zip 파일을 다운로드하는 방법을 선택하셨습니다.

아래 상자는 어떤 저장소 분기를 다운로드할지 결정하는 데 도움이 됩니다.
올바른 시작 프로젝트 버전을 다운로드하지 않으면
설정 과정을 다시 반복해야 합니다.

== 다운로드해야 하는 버전

// 업데이트 할 때 StaterProjectViaClone.adoc, StarterProjectViaZip.adoc, dependencies.adoc 도 같이 업데이트하기 (엔진)
====
이는 문서의 *최신 안정적* 버전입니다.
// 이는 문서의 *개발* 버전입니다.

안정적 (릴리스) 및 실험은 현재 둘 다 1.0 릴리스로 동일한 버전입니다.

SML 3.9.0의 모드를 개발하기 위해 https://github.com/satisfactorymodding/SatisfactoryModLoader/archive/refs/heads/master.zip[여기]를
클릭하여 **`master` 분기**의 zip 파일을 다운로드하십시오.

// Download a zip of the **`dev` branch** (because SML 3.8.? is not released yet)
// by clicking https://github.com/satisfactorymodding/SatisfactoryModLoader/archive/refs/heads/dev.zip[here].

// You should download a zip either of the **`dev` branch** or the **`master` branch**.
// Of those two, you probably want whichever branch was pushed to most recently, which you can see
// https://github.com/satisfactorymodding/SatisfactoryModLoader/branches[on the GitHub repository].

어떤 분기를 선택할 지 모르겠다면 **디스코드에 도움을 요청하십시오**.
====

== 파일 압축 해제

[WARNING]
====
기본적으로 Windows는 인터넷에서 다운로드한 파일을 "차단됨"으로 표시합니다.
이로 인해 나중에 문제가 발생할 수 있습니다.
이 문제를 해결하려면 압축 파일을 우클릭 후 속성 메뉴에서 "차단 해제"한 다음 압축을 해제하십시오.
====
`SatisfactoryModLoader-master.zip` (또는 `-dev.zip`) 을 압축 해제하여 시작 프로젝트 파일을 가져옵니다.
압축 해제에 문제가 있는 경우
https://www.7-zip.org/[7zip] 또는
https://www.win-rar.com/start.html[WinRAR]과 같은
다른 압축 해제 소프트웨어를 사용해 보십시오.

나중에 폴더를 이동할 수 있으며, 가장 상단의 폴더 이름을 원하는 대로 지정할 수 있습니다.

시작 프로젝트 파일을 놓을 좋은 위치를 정하기 위해
xref:Development/BeginnersGuide/StarterProject/ObtainStarterProject.adoc[시작 프로젝트 페이지]에서
참고를 꼭 읽어보십시오.

== 다음 단계

이제 모든 의존성을 설치했으므로
xref:Development/BeginnersGuide/project_setup.adoc[프로젝트 설정]으로 이동할 수 있습니다.

